#!/usr/bin/env bash
###############################################################################
##
##       filename: makefile
##    description: 
##        created: 2023/11/20
##         author: ticktechman
##
###############################################################################
.PHONY: all build test install doc

all:
	flutter build macos --release

run:
	open ./build/macos/Build/Products/Release/layouts.app
###############################################################################
